import type { Metadata } from "next";
import { Barlow, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopMenu from "@/components/topMenu";

import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";

import ClientProviders from "./clientProviders";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

const inter = Inter({ subsets: ["latin"] });
const barlow = Barlow({ weight: ["700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProviders>
      <ClerkProvider>
        <html lang="en">
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          <body className={barlow.className + " " + inter.className}>
            <div className="px-4 md:px-12 lg:px-16 xl:px-24">
              <TopMenu />
              {children}
            </div>
          </body>
        </html>
      </ClerkProvider>
    </ClientProviders>
  );
}
