import type { Metadata } from "next";
import { Barlow, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TopMenu from "@/components/topMenu";

const inter = Inter({ subsets: ["latin"] });
const barlow = Barlow({ weight: ["700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={barlow.className + " " + inter.className}>
          <div className="px-4 md:px-12 lg:px-16 xl:px-24">
            <TopMenu />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
